### ISSUE TITLE
Roadmap to fast-glob@2.0.0

### ISSUE THREAD

**Issue by mrmlnc** [mrmlnc/fast-glob#15]
## ✅ Common

  * [x] Drop `bash-glob` (many questions)
  * [x] Provide Stream API

## ✅ Performance (File System)

  * [x] Combine multiple patterns by base directory of each pattern (further tasks)
  * [ ] Implement recursive `fs.readdir`
    * [ ] Cache between workers in the same run, when there are multiple tasks
  * [ ] Use `fs.scandir` instead of `fs.readdir` + `fs.stat`
    * [ ] Blocked by https://github.com/nodejs/node/issues/15699 (PR?)
    * [x] ~If Node.js will be against `fs.scandir` then create `(scandir|readdir)-native` package~~ (native package is a bad idea)
  * [ ] Sort founded files by `inode` for `fs.stats` calls with `stats` option
  * [x] Add ability to skip ignored directories (like `node_modules`) during the scan

## ✅ Benchmark

  * [x] Rewrite benchmark to TypeScript
  * [x] Add previous version of fast-glob to benchmark to compare performance between versions
  * [x] Add benchmark suites for small, medium and large count of entries in the directory
  
## Release

  * [x] Smoke compare with `globby`
  * [x] Test on real projects
    * [x] `tartifacts`
    * [x] Relay #23 
  * [x] Git Tag & Release announcement 
  * [x] Publish `2.0.0` to npm
  * [x] Change `fast-glob` previous version in the benchmark
  * [x] Use `@types/readdir-enhanced`
  * [x] Twitter

**Comment by mrmlnc** [comment]
## Windows (Appveyor)

<details>

<summary>Raw data (prod)</summary>

```
[1892, 0.1133s] 00-fast-glob.js
[1892, 0.1089s] 01-fast-glob-native.js
[1892, 0.311s] 02-filehound.js
[1892, 0.2527s] 03-glob.js
[1892, 0.2498s] 04-klaw.js
[1892, 0.067s] 05-recursive-readdir.js
[1892, 0.1511s] 06-wildglob.js
[1892, 0.0869s] 07-readdir-enhanced.js
[1892, 0.2703s] 08-globule.js
[1892, 0.2635s] 09-resolve-glob.js
[1892, 0.1635s] 10-readdirp.js
[1892, 0.0902s] 11-readdir-plus.js

MINIMAL:
[0.067s] 05-recursive-readdir.js
```

</details>

<details>

<summary>Raw data (full)</summary>

```
[14134, 0.6296s] 00-fast-glob.js
[14134, 0.6043s] 01-fast-glob-native.js
[14129, 2.1562s] 02-filehound.js
[14134, 2.2186s] 03-glob.js
[14141, 1.8936s] 04-klaw.js
[14135, 0.5386s] 05-recursive-readdir.js
[14134, 0.9197s] 06-wildglob.js
[14135, 0.5934s] 07-readdir-enhanced.js
[14134, 2.2093s] 08-globule.js
[14134, 2.2683s] 09-resolve-glob.js
[14129, 0.9606s] 10-readdirp.js
[14135, 0.5731s] 11-readdir-plus.js

MINIMAL:
[0.5386s] 05-recursive-readdir.js
```

</details>

## Windows (Intel Celeron N3150, 8GB, SSD)

<details>

<summary>Raw data (prod)</summary>

```
[1892, 0.5511s] 00-fast-glob.js 
[1892, 0.5465s] 01-fast-glob-native.js 
[1892, 1.4562s] 02-filehound.js 
[1892, 1.0076s] 03-glob.js 
[1892, 0.8401s] 04-klaw.js 
[1892, 0.3199s] 05-recursive-readdir.js 
[1892, 0.587s] 06-wildglob.js 
[1892, 0.4106s] 07-readdir-enhanced.js 
[1892, 1.1154s] 08-globule.js 
[1892, 1.0201s] 09-resolve-glob.js 
[1892, 0.7372s] 10-readdirp.js 
[1892, 0.3667s] 11-readdir-plus.js 

MINIMAL: 
[0.3199s] 05-recursive-readdir.js
```

</details>

<details>

<summary>Raw data (full)</summary>

```
[14134, 3.3451s] 00-fast-glob.js 
[14134, 3.3871s] 01-fast-glob-native.js 
[14129, 11.218s] 02-filehound.js 
[14134, 7.3282s] 03-glob.js 
[14141, 6.6859s] 04-klaw.js 
[14135, 2.7497s] 05-recursive-readdir.js 
[14134, 4.2295s] 06-wildglob.js 
[14135, 2.9074s] 07-readdir-enhanced.js 
[14134, 9.5224s] 08-globule.js 
[14134, 7.1422s] 09-resolve-glob.js 
[14129, 5.3234s] 10-readdirp.js 
[14135, 2.845s] 11-readdir-plus.js 

MINIMAL: 
[2.7497s] 05-recursive-readdir.js
```

</details>

## Linux

<details>

<summary>Raw data (prod)</summary>

```
[1892, 0.3574s] 00-fast-glob.js
[1892, 0.1651s] 01-fast-glob-native.js
[1892, 0.5142s] 02-filehound.js
[1892, 0.7143s] 03-glob.js
[1892, 0.464s] 04-klaw.js
[1892, 0.1819s] 05-recursive-readdir.js
[1892, 0.3137s] 06-wildglob.js
[1892, 0.2747s] 07-readdir-enhanced.js
[1892, 0.3959s] 08-globule.js
[1892, 0.7515s] 09-resolve-glob.js
[1892, 0.5969s] 10-readdirp.js
[1892, 0.2768s] 11-readdir-plus.js

MINIMAL:
[0.1651s] 01-fast-glob-native.js
```

</details>

<details>

<summary>Raw data (full)</summary>

```
[14135, 1.8101s] 00-fast-glob.js
[14142, 1.0243s] 01-fast-glob-native.js
[14130, 2.6752s] 02-filehound.js
[14135, 4.7454s] 03-glob.js
[14142, 3.9127s] 04-klaw.js
[14136, 1.1854s] 05-recursive-readdir.js
[14135, 2.1902s] 06-wildglob.js
[14136, 1.3845s] 07-readdir-enhanced.js
[14135, 2.4735s] 08-globule.js
[14135, 4.5862s] 09-resolve-glob.js
[14130, 3.0874s] 10-readdirp.js
[14135, 1.6844s] 11-readdir-plus.js

MINIMAL:
[1.0243s] 01-fast-glob-native.js
```

</details>

## Ubuntu (Intel Xeon E312xx 16CPU, 60GB, HDD)

<details>

<summary>Raw data (prod)</summary>

```
[1892, 0.1879s] 00-fast-glob.js
[1892, 0.0714s] 01-fast-glob-native.js
[1892, 0.2809s] 02-filehound.js
[1892, 0.393s] 03-glob.js
[1892, 0.275s] 04-klaw.js
[1892, 0.0862s] 05-recursive-readdir.js
[1892, 0.1994s] 06-wildglob.js
[1892, 0.1335s] 07-readdir-enhanced.js
[1892, 0.2317s] 08-globule.js
[1892, 0.4008s] 09-resolve-glob.js
[1892, 0.2549s] 10-readdirp.js
[1892, 0.1381s] 11-readdir-plus.js

MINIMAL:
[0.0714s] 01-fast-glob-native.js
```

</details>

<details>

<summary>Raw data (full)</summary>

```
[14135, 1.0288s] 00-fast-glob.js
[14142, 0.4871s] 01-fast-glob-native.js
[14130, 1.58s] 02-filehound.js
[14135, 2.9282s] 03-glob.js
[14142, 1.8757s] 04-klaw.js
[14136, 0.6171s] 05-recursive-readdir.js
[14135, 1.285s] 06-wildglob.js
[14136, 0.8008s] 07-readdir-enhanced.js
[14135, 1.487s] 08-globule.js
[14135, 3.0842s] 09-resolve-glob.js
[14130, 1.788s] 10-readdirp.js
[14135, 0.9516s] 11-readdir-plus.js

MINIMAL:
[0.4871s] 01-fast-glob-native.js
```

</details>

## Ubuntu (Common KVM processor 8CPU, 20GB, SSD)

<details>

<summary>Raw data (prod)</summary>

```
[1891, 0.2401s] 00-fast-glob.js
[1891, 0.084s] 01-fast-glob-native.js
[1891, 0.3482s] 02-filehound.js
[1891, 0.5324s] 03-glob.js
[1891, 0.4419s] 04-klaw.js
[1891, 0.1107s] 05-recursive-readdir.js
[1891, 0.2477s] 06-wildglob.js
[1891, 0.171s] 07-readdir-enhanced.js
[1891, 0.3097s] 08-globule.js
[1891, 0.5477s] 09-resolve-glob.js
[1891, 0.3789s] 10-readdirp.js
[1891, 0.1897s] 11-readdir-plus.js

MINIMAL:
[0.084s] 01-fast-glob-native.js
```

</details>

<details>

<summary>Raw data (full)</summary>

```
[1891, 0.2401s] 00-fast-glob.js
[1891, 0.084s] 01-fast-glob-native.js
[1891, 0.3482s] 02-filehound.js
[1891, 0.5324s] 03-glob.js
[1891, 0.4419s] 04-klaw.js
[1891, 0.1107s] 05-recursive-readdir.js
[1891, 0.2477s] 06-wildglob.js
[1891, 0.171s] 07-readdir-enhanced.js
[1891, 0.3097s] 08-globule.js
[1891, 0.5477s] 09-resolve-glob.js
[1891, 0.3789s] 10-readdirp.js
[1891, 0.1897s] 11-readdir-plus.js

MINIMAL:
[0.084s] 01-fast-glob-native.js
```

</details>

## macOS (Intel Core i5, 16GB, SSD)

<details>

<summary>Raw data (prod)</summary>

```
[1892, 0.1298s] 00-fast-glob.js
[1892, 0.0813s] 01-fast-glob-native.js
[1892, 0.1637s] 02-filehound.js
[1892, 0.2868s] 03-glob.js
[1892, 0.1232s] 04-klaw.js
[1892, 0.0734s] 05-recursive-readdir.js
[1892, 0.1123s] 06-wildglob.js
[1892, 0.097s] 07-readdir-enhanced.js
[1892, 0.234s] 08-globule.js
[1892, 0.3035s] 09-resolve-glob.js
[1892, 0.1717s] 10-readdirp.js
[1892, 0.1039s] 11-readdir-plus.js

MINIMAL:
[0.0734s] 05-recursive-readdir.js
```

</details>

<details>

<summary>Raw data (full)</summary>

```
[14630, 0.7967s] 00-fast-glob.js
[14638, 0.7981s] 01-fast-glob-native.js
[14625, 1.1248s] 02-filehound.js
[14630, 2.7724s] 03-glob.js
[14638, 1.1994s] 04-klaw.js
[14632, 0.7255s] 05-recursive-readdir.js
[14630, 1.1177s] 06-wildglob.js
[14632, 0.7943s] 07-readdir-enhanced.js
[14630, 1.771s] 08-globule.js
[14630, 2.6222s] 09-resolve-glob.js
[14625, 1.6945s] 10-readdirp.js
[14631, 0.8126s] 11-readdir-plus.js

MINIMAL:
[0.7255s] 05-recursive-readdir.js
```

</details>

**Comment by mrmlnc** [comment]
Device/Package | glob | fast-glob | fast-glob (n) | implementation | readdir-enhanced | recursive-readdir
-- | -- | -- | -- | -- | -- | --
macOS | 0.30 + 2.24 | 0.12 + 0.76 | 0.08 + 0.72 | 0.10 + 0.72 | 0.12 + 0.75 | 0.10 + 0.68
8CPU | 0.56 + 3.99 | 0.26 + 1.39 | 0.10 + 0.77 | 0.18 + 1.01 | 0.25 + 1.30 | 0.17 + 0.99
16CPU | 0.43 + 3.29 | 0.22 + 1.17 | 0.08 + 0.54 | 0.15 + 0.82 | 0.19 + 1.10 | 0.14 + 0.83
Windows | 1.14 + 9.72 | 0.73 + 3.95 | 0.73 + 3.95 | 0.63 + 3.68 | 0.74 + 4.05 | 0.58 + 3.58

**Comment by mrmlnc** [comment]
Demo repository: https://github.com/pixelass/ava-xo-test/tree/globby
Related issue: https://github.com/sindresorhus/globby/issues/43 

## Globby (wrapper for `node-glob`)

```
pattern: one/a/b/c/d/e/f/g/h/i/j/this-is-it/**/*.js
time:    0.632
files:   53


pattern: one/a/b/c/d/e/f/g/h/**/this-is-it/**/*.js
time:    1.438
files:   53


pattern: one/a/b/c/d/**/this-is-it/**/*.js
time:    17.666
files:   53


pattern: one/a/b/c/**/this-is-it/**/*.js
time:    17.667
files:   53


pattern: **/this-is-it/**/*.js
time:    18.495
files:   53
```

## fast-glob@1 (without `bash-glob`)

```
pattern: one/a/b/c/d/e/f/g/h/i/j/this-is-it/**/*.js
time:    0.037
files:   53


pattern: one/a/b/c/d/e/f/g/h/**/this-is-it/**/*.js
time:    0.14
files:   53


pattern: one/a/b/c/d/**/this-is-it/**/*.js
time:    0.281
files:   53


pattern: one/a/b/c/**/this-is-it/**/*.js
time:    0.304
files:   53


pattern: **/this-is-it/**/*.js
time:    2.428
files:   53
```

## fast-glob@1 (with `bash-glob`)

```
pattern: one/a/b/c/d/e/f/g/h/**/this-is-it/**/*.js
time:    0.036
files:   53


pattern: one/a/b/c/d/e/f/g/h/i/j/this-is-it/**/*.js
time:    0.041
files:   53


pattern: one/a/b/c/d/**/this-is-it/**/*.js
time:    0.054
files:   53


pattern: one/a/b/c/**/this-is-it/**/*.js
time:    0.064
files:   53


pattern: **/this-is-it/**/*.js
time:    0.649
files:   53
```

## fast-glob@2

```
pattern: one/a/b/c/d/e/f/g/h/i/j/this-is-it/**/*.js
time:    0.037
files:   53


pattern: one/a/b/c/d/e/f/g/h/**/this-is-it/**/*.js
time:    0.141
files:   53


pattern: one/a/b/c/d/**/this-is-it/**/*.js
time:    0.266
files:   53


pattern: one/a/b/c/**/this-is-it/**/*.js
time:    0.288
files:   53


pattern: **/this-is-it/**/*.js
time:    2.483
files:   53
```

**Comment by elevatebart** [comment]
"founded files" took me a while to understand. I think you mean "found files"
